### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by choeppler** [accordproject/docs#2]
The document on [Fees, Contributions and Level Benefits](https://github.com/accordproject/docs/blob/master/Accord%20Project%20Participant%20Types%20and%20Fee%20and%20Contribution%20Schedule.pdf) linked to from README.md has been missing in master (currently at 3977b426d6a585983c3aa63bcf0236021e197c43) for a few months...

**Comment by peterhunn** [comment]
As the fees are completely removed, the docs have been updated to reflect this. The errant link has now been removed. Thank you for flagging.
